### ISSUE TITLE
Unable to access any routes

### ISSUE THREAD

**Issue by deardooley** [BigstickCarpet/swagger-express-middleware#1]
I'm trying to mock out this api definition,

https://github.com/deardooley/agave-mock-tags-api/blob/master/tags.yaml

But I can't access any routes, persist any data, or do much of anything other than serve up the swagger doc itself. Any idea what could be going on? I tried with both node server samples.

**Comment by BigstickCarpet** [comment]
Are you browsing to the right URL?  The `basePath` is set to `/mock`, so you'll have to browse to `/mock/tags`, `/mock/tags/{tagId}`, `/mock/tags/{tagId}/resources`, etc.

When I browse to `/mock/tags`, I see the following error message:

````
Error: 500 Error: Invalid JSON schema type: undefined
````

The issue here is that the `MultipleTagResponse` definition doesn't have a `type` property specified.  If you add `type: object`, it'll work.   

Per the Swagger 2.0 spec, all definitions, parameters, etc. require a `type` to be specified.  It doesn't default to `object`.   I plan to add a check for this to [Swagger Parser](https://github.com/BigstickCarpet/swagger-parser) so that the Swagger API will fail validation if any types are missing.   Right now, it passes validation, and then you get an error in the Mock middleware.

**Comment by deardooley** [comment]
Got it! That makes a huge difference. I’m having an issue routing to sub collections of generated mock data, but I’ll submit that as another issue.

—
Rion
