### ISSUE TITLE
404 when requesting mock subcollections

### ISSUE THREAD

**Issue by deardooley** [BigstickCarpet/swagger-express-middleware#2]
I've created a set of mock sample data with primary resources and two subresources populated with data. [https://github.com/deardooley/agave-tags-swagger-middleware](https://github.com/deardooley/agave-tags-swagger-middleware). I'm able to browse to the primary resources collection and individual resources successfully:

> http://localhost:8000/tags
> http://localhost:8000/tags/0

I can also reference the subresources by direct link without problem:

> http://localhost:8000/tags/0/resources/0
> http://localhost:8000/tags/0/pems/Janie86

However I cannot view the subcollections

> http://localhost:8000/tags/0/resources
> http://localhost:8000/tags/0/pems

Any idea why this could be?

**Comment by BigstickCarpet** [comment]
The Mock middleware determines whether a path is a collection or a resource based on the `get` operation's response schema. ([more info here](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#1-determine-if-its-a-collection-or-resource-operation))  If the response is an array, then it's a collection path; otherwise, it's a resource path.   In your case, the `/tags/{tagId}/resources` and `/tags/{tagId}/pems` paths both return objects, not arrays, so they're being treated as resource paths.

There's a couple ways to workaround this:

1. You could change the response schemas to be arrays instead of objects.  Right now, your _actual_ results (which _are_ arrays) are wrapped in objects that have extra properties for error, status, and version.  You could get rid of the object wrapper and just return the arrays directly.  A good practice in RESTful APIs is to use HTTP error codes to convey error information, so you don't need to include that as part of a 200 (success) response.  As for API version... that could be sent as an HTTP header.

2. You could leave everything as-is, and write [custom middleware to set the response data](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#modifying-the-response) the way you want to for the `/tags/{tagId}/resources` and `/tags/{tagId}/pems` paths.

**Comment by deardooley** [comment]
Without getting into dogmatic REST design, how do you handle paginated sets, contextual messages, etc for complex operations without providing a response wrapper?

—
Rion

**Comment by BigstickCarpet** [comment]
Yeah, there are definitely times when _dogmatic_ REST design has to give-in to _pragmatic_ REST design.  

My personal preference is to use HTTP headers for anything other than the _actual_ response data.  So, for paginated search results, the response body would contain the actual results (one page's worth), and I'd use a header to indicate which page of results it is, and how many other pages there are. 

But my goal is for the Mock middleware to be as flexible as possible, so it can work with a wide variety of different REST designs - not just my personal preferences.   I'm totally open to ideas on how to improve the collection-vs-resource logic.  If there's a way to intuitively determine when an `object` response schema is actually a collection, I'm open to implementing it.

**Comment by deardooley** [comment]
I can see the value in that approach. On my end, I just hate header parsing and manipulation on the client side. It’s a smidgen easier for me to parse and respond to those things in the body when wiring up UI. You’re right, though. Flip a coin. I’d rather be done and paid than be "correct."

I also see that your middleware is completely correct in how it’s not returning anything. Given the definition I have, the only way it could catch that write a data store that’s essentially a poor man’s ORM based on the swagger defs, validate the data on ingestion, persist it as a valid decomposed domain model, then reform it from the model definitions in the response. Your project + that piece are basically the silver bullet to API prototyping. I’ve done it in Laravel for a few recent projects by forking the generator plugin, but not in node or java. I’m not sure what the return on doing it is in the short term, but I’ll add it to the list. If I wind up writing it, I’ll issue a pull request to contribute back.

—
Rion

**Comment by BigstickCarpet** [comment]
In lieu of a poor man's ORM, something like this should work for now:

````javascript
var _ = require('lodash');

app.get('/tags/:tagId/resources', function(req, res, next) {
    myDB.getCollection('/tags/' + req.params.tagId + '/resources', function(err, resources) {
        res.json({
            status: 'success',
            message: '',
            version: '0.1.0',
            result: _.pluck(resources, 'data')
        });
    });
});
````

**Comment by deardooley** [comment]
I could template it out, I suppose. I have 5-6 other apis with another 60 or so resources (summary + full). guess we’ll figure it out under fire.

—
Rion

**Comment by BigstickCarpet** [comment]
@deardooley - Good news!  Do an `npm update`, and everything should work for you now.   I figured out a way to enhance the resource-vs-collection logic to support wrapper-objects such as your `MultipleTagResourceResponse` and `MultipleTagPermissionResponse` objects.   The trick is that the "wrapped" data type (e.g. `TagResource` and `TagPermission`) matches the `body` parameter of your `POST` operation.  That's enough information for me to reliably infer the proper relationship.

By default, the Mock middleware won't populate any of the properties of your wrapper object.  So, for example, your `MultipleTagResourceResponse` will just look like this:

````javascript
{
    result: [ /* TagResource objects here */ ]
}
````

You can specify `default` or `example` values in your Swagger API like this:

````yaml
MultipleTagResourceResponse:
  type: object
  description: Generic wrapper with list of TagResource as result
  properties:
    status:
      description: success or error
      type: string
      default: success
    message:
      description: error message description
      type: string
      default: ""
    version:
      description: api version
      type: string
      version: 0.1.0
    result:
      description: actual TagResource result object
      type: array
      items:
        $ref: "#/definitions/TagResource"
````

Which will make your `MultipleTagResourceResponse` look like this:

````javascript
{
    status: "success",
    message: "",
    version: "0.1.0",
    result: [ /* TagResource objects here */ ]
}
````

Give it a try when you get a chance and let me know what you think.

**Comment by deardooley** [comment]
I think you are a friggin rock star. Thank you!

--
Rion

----- Reply message -----
