### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by leolorenzoluis** [BigstickCarpet/swagger-express-middleware#73]
There's a bunch of PR and last commit was months ago.

**Comment by LandonSchropp** [comment]
I'll be a bit bummed if this is dead. I was really hoping to use this on our current project.

**Comment by BigstickCarpet** [comment]
Hi.  Thanks for the question.  I promise that I have not intentionally abandoned this project.  In fact, I still have a long wishlist of new features and improvements, and I was just talking with a friend of mine last week about our plans to implement some of those features soon.

That said... there are not enough hours in a day.  :(   

Back when originally created Swagger Express Middleware, I was getting paid to do it as part of my job because the company I worked for needed it.  Then last year, partly _because_ of my work on Swagger Express Middleware, I landed a dream job working at [Postman](http://getpostman.com).  It's a great job and I love it, but it keeps me busy for 10 to 12 hours a day, 5 or 6 days a week, and sadly, working on Swagger Express Middleware is not part of the job.  So, between work and family commitments, I'm only left with a few hours each week to work on open-source stuff, and some of my other projects have been higher priority lately, hence the lack of activity on this one.

So what's going to change?  Well... first of all, my workload will (hopefully) be getting lighter soon, because the product that I've been feverishly building for the past year [just launched](https://www.sdxcentral.com/articles/news/postman-releases-postman-pro-provide-api-monitoring/2016/12/) this week.  And secondly, a friend and former co-worker of mine (who helped me build this project at our old company) has offered to help me work on it.  Our work will start with some [other](https://github.com/BigstickCarpet/swagger-parser) [projects](https://github.com/BigstickCarpet/json-schema-ref-parser) that Swagger Express Middleware uses under the hood, so you may not see much activity here until we're ready to start updating this project to use the latest versions of those dependencies.

**Comment by leolorenzoluis** [comment]
Thank you for the comprehensive update. That's what I thought when looking at the history. It did look like you work on it full time, but then obviously life changes. Thank you for open sourcing this project and will look forward to the next activities and good luck in Postman! 👍 

(Hopefully, you can merge all the PR without even adding new features so people won't feel left behind in this project.) :)
